#!/usr/bin/env python3
"""
Semantic-Focused Prompt Optimization

Prioritizes semantic accuracy over brevity. The goal is to match the CONCEPT 
that the golden labels identify, not just make labels shorter.
"""

from pathlib import Path
from typing import Dict, List, Tuple
import random
from label_evaluation import extract_golden_features, extract_autogenerated_features, calculate_semantic_similarity

def analyze_semantic_failures(golden_features: Dict, autogen_features: Dict) -> Dict:
    """Analyze where semantic matching fails most badly."""
    
    failures = []
    overlap = set(golden_features.keys()) & set(autogen_features.keys())
    
    for key in overlap:
        golden_label = golden_features[key]
        autogen_label = autogen_features[key]
        sim = calculate_semantic_similarity(golden_label, autogen_label)
        
        failures.append({
            'key': key,
            'golden': golden_label,
            'autogen': autogen_label[:100] + '...' if len(autogen_label) > 100 else autogen_label,
            'similarity': sim,
            'failure_type': classify_failure_type(golden_label, autogen_label)
        })
    
    # Sort by worst semantic similarity
    failures.sort(key=lambda x: x['similarity'])
    
    return analyze_failure_patterns(failures)

def classify_failure_type(golden: str, autogen: str) -> str:
    """Classify the type of semantic failure."""
    
    golden_lower = golden.lower()
    autogen_lower = autogen.lower()
    
    # Check for specific failure patterns
    if any(word in golden_lower for word in ['name', 'person', 'proper']):
        if 'name' in autogen_lower or 'proper' in autogen_lower:
            return 'correct_category_too_generic'  # Right idea, too verbose
        else:
            return 'missed_name_concept'  # Completely missed it's about names
    
    elif any(word in golden_lower for word in ['punctuation', 'colon', 'period', 'bracket']):
        if any(punct in autogen_lower for punct in ['punctuation', 'colon', 'period']):
            return 'correct_punctuation_verbose'
        else:
            return 'missed_punctuation_concept'
    
    elif any(word in golden_lower for word in ['code', 'syntax', 'programming', 'html', 'css']):
        if any(tech in autogen_lower for tech in ['code', 'syntax', 'programming', 'html']):
            return 'correct_technical_verbose'
        else:
            return 'missed_technical_concept'
    
    elif len(golden.split()) == 1 and len(autogen.split()) > 10:
        return 'specific_word_vs_generic_description'
    
    else:
        return 'generic_mismatch'

def analyze_failure_patterns(failures: List[Dict]) -> Dict:
    """Analyze patterns in semantic failures."""
    
    failure_types = {}
    for failure in failures:
        failure_type = failure['failure_type']
        if failure_type not in failure_types:
            failure_types[failure_type] = []
        failure_types[failure_type].append(failure)
    
    print("SEMANTIC FAILURE ANALYSIS")
    print("=" * 40)
    
    for failure_type, examples in failure_types.items():
        print(f"\n🎯 {failure_type.upper()}: {len(examples)} cases")
        print("Examples:")
        for example in examples[:3]:  # Show top 3 worst cases
            print(f"  Golden: '{example['golden']}'")
            print(f"  Autogen: '{example['autogen']}'")
            print(f"  Similarity: {example['similarity']:.3f}")
            print()
    
    return {
        'failure_types': failure_types,
        'total_failures': len(failures),
        'worst_cases': failures[:10]
    }

def create_semantic_focused_prompts(golden_features: Dict, autogen_features: Dict) -> Dict[str, str]:
    """Create prompts that specifically target semantic accuracy."""
    
    # Analyze failures to understand what's going wrong
    analysis = analyze_semantic_failures(golden_features, autogen_features)
    
    # Extract examples that show CORRECT semantic concepts
    good_examples = []
    overlap = set(golden_features.keys()) & set(autogen_features.keys())
    
    # Find any cases where semantic similarity is decent
    for key in overlap:
        golden_label = golden_features[key]
        autogen_label = autogen_features[key]
        sim = calculate_semantic_similarity(golden_label, autogen_label)
        if sim > 0.1:  # Any decent matches
            good_examples.append((golden_label, autogen_label, sim))
    
    # Group golden labels by concept type for few-shot examples
    concept_groups = {
        'names': [v for k, v in golden_features.items() if any(word in v.lower() for word in ['name', 'person', 'proper'])],
        'punctuation': [v for k, v in golden_features.items() if any(word in v.lower() for word in ['punctuation', 'colon', 'period', 'bracket'])],
        'technical': [v for k, v in golden_features.items() if any(word in v.lower() for word in ['code', 'syntax', 'html', 'css', 'programming'])],
        'linguistic': [v for k, v in golden_features.items() if any(word in v.lower() for word in ['verb', 'noun', 'adjective', 'suffix', 'prefix'])],
        'domain_specific': [v for k, v in golden_features.items() if any(word in v.lower() for word in ['sports', 'legal', 'medical', 'academic'])]
    }
    
    prompts = {}
    
    # Semantic-First Prompt
    prompts['semantic_first'] = create_semantic_first_prompt(concept_groups)
    
    # Contrastive Semantic Prompt  
    prompts['contrastive_semantic'] = create_contrastive_semantic_prompt(analysis)
    
    # Chain-of-Thought Semantic
    prompts['cot_semantic'] = create_cot_semantic_prompt(concept_groups)
    
    return prompts

def create_semantic_first_prompt(concept_groups: Dict[str, List[str]]) -> str:
    """Prompt that prioritizes semantic accuracy above all else."""
    
    examples_by_category = []
    for category, labels in concept_groups.items():
        if labels:
            sample_labels = random.sample(labels, min(3, len(labels)))
            examples_by_category.append(f"{category.title()}: {', '.join(f'"{label}"' for label in sample_labels)}")
    
    examples_text = "\n".join(examples_by_category)
    
    return f"""You are a neural network interpretability expert. Your PRIMARY goal is semantic accuracy - identifying the exact concept this feature detects.

CONCEPT EXAMPLES from expert annotations:
{examples_text}

CRITICAL: Focus on WHAT CONCEPT the feature detects, not HOW to describe it.

SEMANTIC ACCURACY CHECKLIST:
1. Does this feature detect names/people? → Use "names" or specific type
2. Does it detect punctuation? → Use "punctuation" + type (colon, period)  
3. Does it detect code/syntax? → Use "code" or specific syntax type
4. Does it detect specific words? → Name the actual word/concept
5. Does it detect linguistic patterns? → Use linguistic terms (suffix, verb, etc)

WRONG: "Various tokens that often appear in contexts" (meaningless)
RIGHT: "Proper names" (identifies the actual concept)

WRONG: "Words with particular characteristics" (vague)  
RIGHT: "Comparative adjectives" (specific linguistic concept)

Your explanation should capture the SEMANTIC ESSENCE of what this feature detects.

{{prompt}}"""

def create_contrastive_semantic_prompt(analysis: Dict) -> str:
    """Prompt using contrastive examples of semantic success/failure."""
    
    worst_cases = analysis.get('worst_cases', [])
    examples = []
    
    for case in worst_cases[:5]:
        examples.append(f"❌ WRONG: '{case['autogen'][:80]}...' (for golden: '{case['golden']}')")
    
    examples_text = "\n".join(examples)
    
    return f"""You are a neural network feature analyst. Your job is to identify the CORE CONCEPT this feature detects.

COMMON MISTAKES TO AVOID:
{examples_text}

The pattern in these mistakes: They describe HOW text looks instead of WHAT CONCEPT is being detected.

CORRECT APPROACH:
- Golden label "names" → Feature detects proper names/people
- Golden label "colon punctuation" → Feature detects colon symbols  
- Golden label "sports scores" → Feature detects numerical scores in sports
- Golden label "led" → Feature detects the specific word "led"

SEMANTIC RULES:
1. If golden experts labeled it with a specific word → Look for that exact word/concept
2. If labeled with a category (names, punctuation) → Identify that category
3. If labeled with technical terms → Use precise technical language
4. NEVER say "various", "common", "often", "patterns", "contextual"

Ask yourself: "What specific thing would a human expert say this feature detects?"

{{prompt}}"""

def create_cot_semantic_prompt(concept_groups: Dict[str, List[str]]) -> str:
    """Chain-of-thought prompt focused on semantic reasoning."""
    
    return f"""You are a neural network interpretability researcher. Use systematic reasoning to identify what concept this feature detects.

REASONING PROCESS:
1. EXAMINE THE EXAMPLES: What specific words/patterns are marked?
2. IDENTIFY THE CATEGORY: Names? Punctuation? Technical terms? Linguistic patterns? 
3. FIND THE CORE CONCEPT: What would an expert call this pattern?
4. VERIFY SEMANTIC ACCURACY: Does your label capture the true concept?

Step 1: List the specific words/tokens that activate this feature
Step 2: What category do they belong to? (Use these expert categories as guides)
   - Names/People: {len(concept_groups.get('names', []))} expert examples
   - Punctuation: {len(concept_groups.get('punctuation', []))} expert examples  
   - Technical/Code: {len(concept_groups.get('technical', []))} expert examples
   - Linguistic: {len(concept_groups.get('linguistic', []))} expert examples
   - Domain-specific: {len(concept_groups.get('domain_specific', []))} expert examples
Step 3: What is the precise concept? (Be specific, not generic)
Step 4: Semantic check - would an expert agree this captures the concept?

[EXPLANATION]: [Your semantically accurate label]

{{prompt}}"""

def main():
    """Main semantic optimization analysis."""
    
    print("SEMANTIC ACCURACY OPTIMIZATION")
    print("=" * 50)
    
    # Load data
    golden_path = Path("gemma-michael-jordan_2025-09-09T16-08-55-746Z.json")
    explanations_dir = Path("results/quantized_32b_run/explanations")
    
    if not golden_path.exists() or not explanations_dir.exists():
        print("❌ Data files not found")
        return
    
    golden_features = extract_golden_features(golden_path)
    autogen_features = extract_autogenerated_features(explanations_dir)
    
    print(f"📊 Analyzing semantic accuracy on {len(set(golden_features.keys()) & set(autogen_features.keys()))} overlapping features\n")
    
    # Create semantic-focused prompts
    optimized_prompts = create_semantic_focused_prompts(golden_features, autogen_features)
    
    # Save prompts
    output_dir = Path("semantic_optimized_prompts")
    output_dir.mkdir(exist_ok=True)
    
    for name, prompt in optimized_prompts.items():
        with open(output_dir / f"{name}.txt", 'w') as f:
            f.write(prompt)
    
    print(f"\n✅ Created {len(optimized_prompts)} semantic-focused prompts in {output_dir}/")
    print("\n🎯 NEXT STEPS FOR SEMANTIC IMPROVEMENT:")
    print("1. Try the 'semantic_first' prompt - focuses purely on concept identification")
    print("2. Use 'contrastive_semantic' - shows your current mistakes explicitly")  
    print("3. Test 'cot_semantic' - systematic reasoning about the concept")
    print("4. Measure semantic similarity improvement (should go from 0.004 → 0.3+)")

if __name__ == "__main__":
    main()